### ISSUE TITLE
Missing assigned simple products

### ISSUE THREAD

**Issue by matthiashamacher** [Agence-DnD/PIMGento-2-API#118]
Hello,
we currently have the problem, that not all simple products were assigned to the configurable product during the product import. For example, we have a product with 108 simple products. After the import in Magento the configurable product has only 41 products under configurations, but all 108 products are correctly imported.

I debugged through the import process and the main problem is in Pimgento/Api/Job/Product::createConfigurable(). In the select configurable query, there are only 41 SKU's listed in the _children field. But if you select all products with the specific parent SKU there are 108 rows.

We are using Magento 2.3.1 and Pimgento 100.2.4 (but also tried with Pimgento 100.2.5).

**Comment by Dnd-Gimix** [comment]
Hello @matthiashamacher ,

We have released a new version of the connector, containing a fix for simple product assignation with a variant attribute using uppercase character, causing association to fail : https://github.com/Agence-DnD/PIMGento-2-API/releases/tag/v100.2.6

Could you test again with this new release and tell us if it fixed your issue ?

Thank you.

Regards,

**Comment by matthiashamacher** [comment]
Hello @Dnd-Gimix ,

I just checked it, but unfortunately, nothing had changed. I imported all types but there are still only 41 products assigned to the configurable product.

Kind regards

**Comment by simonrl** [comment]
Hi, did you solve this?

**Comment by matthiashamacher** [comment]
Hi @simonrl,
no, it is still not working. Also tested newest Version 100.2.7

Kind regards.

**Comment by Dnd-Gimix** [comment]
Hello,

As announced on July 25, the repository PIMGento 2 API will be closed by the end of next week. 
Please make sure to check the new connector "Akeneo Connector for Magento 2", available on the Akeneo Github at this address : https://github.com/akeneo/magento2-connector-community

We took note of your issue and we will make sure to provide a fix if necessary on the new version of the connector.

Thank you for your contribution on this repository, we hope to see you back on the new repository !

Have a good day.

Regards,
